# Generated by Django 3.2.9 on 2021-12-03 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Seance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=75, verbose_name='Titre de la séance')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description de la séance')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Seance',
                'verbose_name_plural': 'Seances',
            },
        ),
    ]
