# Generated by Django 3.2.9 on 2021-12-03 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0002_seance_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='seance',
            name='nb_participants',
            field=models.IntegerField(default=0, verbose_name='Nombre de participants'),
        ),
    ]
